// Generated by gencpp from file service/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_MESSAGE_ADDTWOINTS_H
#define SERVICE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service/AddTwoIntsRequest.h>
#include <service/AddTwoIntsResponse.h>


namespace service
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service::AddTwoInts > {
  static const char* value()
  {
    return "service/AddTwoInts";
  }

  static const char* value(const ::service::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::service::AddTwoInts >
template<>
struct MD5Sum< ::service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service::AddTwoInts >::value();
  }
  static const char* value(const ::service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::AddTwoIntsRequest> should match
// service_traits::DataType< ::service::AddTwoInts >
template<>
struct DataType< ::service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service::AddTwoInts >::value();
  }
  static const char* value(const ::service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::service::AddTwoInts >
template<>
struct MD5Sum< ::service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service::AddTwoInts >::value();
  }
  static const char* value(const ::service::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::AddTwoIntsResponse> should match
// service_traits::DataType< ::service::AddTwoInts >
template<>
struct DataType< ::service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service::AddTwoInts >::value();
  }
  static const char* value(const ::service::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_MESSAGE_ADDTWOINTS_H
